name: Create artifacts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build
      run: make

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: minesweeper
        path: build/minesweeper
